### ISSUE TITLE
Search not working anymore

### ISSUE THREAD

**Issue by gpapin** [ChrisAlderson/extratorrent-api#8]
I've been using this plugins for months but it has stopped working recently, I get this error:

```
TypeError: Cannot read property '1' of null
    at ExtraTorrentAPI._formatPage (/Users/projects/comand/lib/extratorrent-api/extratorrent-api.js:69:100)
    at _get.then.res (/Users/projects/comand/lib/extratorrent-api/extratorrent-api.js:144:68)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by gpapin** [comment]
The above trace alterne with this one : 
```
(node:92517) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.
Error: No data found for uri: '/advanced_search/', statuscode: 503
    at Request._request [as _callback] (/Users/projects/comand/lib/extratorrent-api/extratorrent-api.js:58:25)
    at Request.self.callback (/Users/projects/comand/lib/extratorrent-api/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/Users/projects/comand/lib/extratorrent-api/node_modules/request/request.js:1081:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/Users/projects/comand/lib/extratorrent-api/node_modules/request/request.js:1001:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by betomoretti** [comment]
+1 

Specifically, this regexp stop working:

`const et = text.match(/function\set\(\)\{return\s\"(\d+)\";\}/i)[1];`

**Comment by ChrisAlderson** [comment]
I know about the problem, but haven't been able to solve it because ExtraTorrent is a bit of a pain in the rear.

That being said, @gpapin the 'alternate' stacktrace you showed is just one where the request to ExtraTorrent was returned with a 503 error, it has nothing to do with this issue.

Also @betomoretti the regex works, it seems like they encrypt some of their HTML body with AES. I don't know why they are doing that but the HTML I get from a HTTP GET response can be viewed [here](https://gist.github.com/ChrisAlderson/f7bbe9f2886a0dee8adab07ed6a589e5).

**Comment by ChrisAlderson** [comment]
Master branch should work, but I don't know for how long since they seem to be changing a few things. So we will see how long this will last.

**Comment by gpapin** [comment]
Thanks, I get the list back from the site now ! :)  I still have a 503 when trying to download anything from this list but not sure you can do something about this one...

**Comment by gpapin** [comment]
Oh dear... It was working yesterday but it's broken again :( 
Same error:
```
TypeError: Cannot read property '1' of null
    at ExtraTorrentAPI._formatPage (/Users/gpapin/projects/comand/lib/extratorrent-api/extratorrent-api.js:86:100)
    at _get.then.res (/Users/gpapin/projects/comand/lib/extratorrent-api/extratorrent-api.js:157:25)
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

**Comment by goto-10** [comment]
The encryption was added back again so the crypto-js parts of the script should also be added back again.
Here is the current logic to get the encryption key:

```
    let $ = cheerio.load(res);

    const hashObject = $('div#e_content').text();
    const salt = JSON.parse(hashObject).s;

    const latestNewsId = $('.ten_articles li a').eq(0).attr('href').split('le/')[1].split('/')[0];
    const extraNum = $('.ten_len').length; // might be added dynamically
    //console.warn(salt, latestNewsId, extraNum);
    const key = salt[1] + extraNum + extraNum + '0' + latestNewsId + salt[5];

    const data = JSON.parse(CryptoJS.AES.decrypt(hashObject, key, {
      format: CryptoJSAesJson
    }).toString(CryptoJS.enc.Utf8));

    $ = cheerio.load(data);

    const total_results = parseInt(data.match(/total\s\<b\>(\d+)\<\/b\>\storrents\sfound/i)[1]);

```
Currently it seems that the devs at ET are determined block proxies from scraping the torrent list so this might not last long. :(

**Comment by ChrisAlderson** [comment]
I'm not sure what they are doing, but it is damn annoying. I have fixed the issue (although I get a lot of 50x errors atom), but I won't be putting it on npm as of yet. This is because extratorrent is a bitch right now and after they calmed down their side of things I will push it on npm. So for now just use the github link inside the `package.json`.
