### ISSUE TITLE
Malformed UTF-8 data

### ISSUE THREAD

**Issue by gpapin** [ChrisAlderson/extratorrent-api#9]
It looks like ET have changed again.

I get this error when using the search:

```
Error: Malformed UTF-8 data
    at Object.stringify (/lib/extratorrent-api/node_modules/crypto-js/core.js:478:24)
    at WordArray.init.toString (/lib/extratorrent-api/node_modules/crypto-js/core.js:215:38)
    at ExtraTorrentAPI._formatPage (/lib/extratorrent-api/extratorrent-api.js:123:8)
    at _get.then.res (/lib/extratorrent-api/extratorrent-api.js:198:25)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Error searching extratorrent
```

**Comment by goto-10** [comment]
Here is the new logic, change it in **_formatPage** function

```  
    let $ = cheerio.load(res);

    const hashObject = $('div#e_content').text();
    const salt = JSON.parse(hashObject).s;

    const newsId = $('.ten_articles li a').eq(3).attr('href').split('le/')[1].split('/')[0];
    const extraNum = $('.ten_len').length; // might be added dynamically
    //console.warn(salt, newsId, extraNum);
    const key = salt[5] + '0' + extraNum + '0' + newsId + salt[2];

    const data = JSON.parse(CryptoJS.AES.decrypt(hashObject, key, {
      format: CryptoJSAesJson
    }).toString(CryptoJS.enc.Utf8));

    $ = cheerio.load(data);

    const total_results = parseInt(data.match(/total\s\<b\>(\d+)\<\/b\>\storrents\sfound/i)[1]);
```

**Comment by ChrisAlderson** [comment]
@goto-10 Thanks, I pushed your changed to `master`.

**Comment by gpapin** [comment]
Thank you guys :)
